feat: add allowShortCircuit and allowTernary rules
Fix for issue:
TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
 Occurred while linting /home/ext4cats/Projects/tseslint-8.14.0-bug/index.js